version: '3.9'
services:
  db:
    image: mongo:5
    restart: always
    ports:
      - 27018:27017
    environment:
      MONGO_DATABASE: nest-pokemon
    volumes:
      - mongo-data: /data/db
volumes:
  mongo-data:
